### ISSUE TITLE
NuGet Packages

### ISSUE THREAD

**Issue by hhenrique** [shintadono/OpenGL.Core#1]
Hi,
I couldn't find any NuGet packages for OpenGL.Core, Win32, and Win32.WGL. Do you have plans to publish them? I could help.

**Comment by shintadono** [comment]
Hi, I never really bothered with publishing, never learnt what that actually encompasses. I preferred using such repos as submodules (easier to debug into). But feel free to fork or copy them, and publish them on your own. Though, I probably won't do any work on them anytime soon.
